name: Static Analysis

on:
  push:
  pull_request:

jobs:
  Tests:
    name: Static Analysis (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
    continue-on-error: ${{ matrix.php == '8.5' }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install Dependencies with Composer
        run: composer install --ignore-platform-req=php+

      - name: Static Code Analysis
        run: vendor/bin/phpstan
